"""Initial migration

Revision ID: 3b2f574a2cf2
Revises: 
Create Date: 2025-11-23 16:17:56.053657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b2f574a2cf2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=128), nullable=False),
    sa.Column('security_token', sa.String(length=64), nullable=False),
    sa.Column('personality_type', sa.String(length=50), nullable=False),
    sa.Column('evolved', sa.Boolean(), nullable=False),
    sa.Column('affection', sa.Integer(), nullable=False),
    sa.Column('tsundere_score', sa.Integer(), nullable=False),
    sa.Column('yandere_score', sa.Integer(), nullable=False),
    sa.Column('kuudere_score', sa.Integer(), nullable=False),
    sa.Column('dandere_score', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('long_term_memories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('long_term_memories')
    op.drop_table('chat_messages')
    op.drop_table('users')
    # ### end Alembic commands ###
